urls.py
from django.urls import path
from . import views

app_name = "nibble"

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('board/<int:pk>', views.BoardView.as_view(), name='board'),
    path('archive/<int:pk>', views.ArchiveView.as_view(), name='archive'),
    # Card views
    path('card/<int:pk>', views.CardView.as_view(), name='card'),
    path('card/create/', views.CardCreateView.as_view(), name='card_create'),
    path('card/edit/<int:card_id>/<str:field_name>/', views.CardEditView.as_view(), name="card_edit"),
    # Attachment views
    path('attachment/create/', views.AttachmentCreateView.as_view(), name='attachment_create'),
    path('attachment/edit/<int:attachment_id>/', views.AttachmentEditView.as_view(), name="attachment_edit"),
    path('attachment/delete/<int:pk>', views.AttachmentDeleteView.as_view(), name="attachment_delete"),
    # Comment views
    path('comment/create/', views.CommentCreateView.as_view(), name='comment_create'),
    path('comment/edit/<int:comment_id>', views.CommentEditView.as_view(), name="comment_edit"),
    path('comment/delete/<int:pk>', views.CommentDeleteView.as_view(), name="comment_delete"),
    # Checklist views
    path('checklist/create', views.ChecklistCreateView.as_view(), name="checklist_create"),
    path('checklist/edit/<int:checklist_id>/<str:field_name>/', views.ChecklistEditView.as_view(), name="checklist_edit"),
    path('checklist/delete/<int:pk>', views.ChecklistDeleteView.as_view(), name="checklist_delete"),
    # Task views
    path('task/create', views.TaskCreateView.as_view(), name="task_create"),
    path('task/edit/<int:task_id>/<str:field_name>/', views.TaskEditView.as_view(), name="task_edit"),
    path('task/delete/<int:pk>', views.TaskDeleteView.as_view(), name="task_delete"),
    # Profile views
    path('profile/<str:handle>',views.ProfileDetailView.as_view(), name='profile'),

]

templates/nibble/forms/attachment_delete_confirmation_modal.html
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteModalLabel">Delete {{attachment.name}}?</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <form hx-delete="{% url 'nibble:attachment_delete' attachment.id %}" hx-target="#attachment-{{attachment.id}}" hx-swap="delete" hx-on::after-request="this.reset(); bootstrap.Modal.getInstance(document.getElementById('deleteModal')).hide()"
                class="swappableClass">
                <div class="modal-body">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Delete!</button>
                    <button type="button" data-bs-dismiss="modal">Cancel</button>
            </form>
        </div>
    </div>
</div>

templates/nibble/forms/attachment_form.html
<form hx-post="{% url 'nibble:attachment_edit' attachment_id %}" hx-target="#attachment-{{attachment_id}}" hx-swap="outerHTML" class="swappableClass">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Name" value="{{name_value}}" required>
    <input type="url" name="url" placeholder="URL" value="{{url_value}}" autofocus required>
    <input type="hidden" name="card" value="{{card_id}}">
    <button type="submit">💾</button>
  </form>

templates/nibble/forms/card_create_form.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal{{column}}">
    Add new
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal{{column}}" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add new</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            
            <form hx-post="{% url 'nibble:card_create' %}" hx-target="#column{{column}}" hx-swap="beforeend" hx-on::after-request="this.reset(); bootstrap.Modal.getInstance(document.getElementById('exampleModal{{column}}')).hide()"
                class="swappableClass">
                <div class="modal-body">
                    {% csrf_token %}

                    <input type="text" name="name" autofocus>
                    <input type="hidden" name="column" value="{{column}}">
            
                    <button type="submit" class="btn btn-primary">💾</button>
          
            </form>
        </div>
    </div>
</div>
</div>

templates/nibble/forms/card_edit_form.html
<form hx-post="{% url 'nibble:card_edit' card_id field_name %}" hx-target="this" hx-swap="outerHTML" class="swappableClass">
  {% csrf_token %}

  {% if field_name == "due_datetime" %}
    <input type="datetime-local" name="{{field_name}}" value="{{field_value}}" autofocus>
  {% elif field_name == "owner" or field_name == "helper" %}
    {% for user in user_list %}
    <input type="radio" name="{{field_name}}" value="{{user.id}}">
      {{user.handle}}
    {%endfor%}
    {% elif field_name == "label" %}
    {% for label in label_list %}
    <div style="display:inline">
    <input class="form-check-input" type="checkbox" name="{{field_name}}" id="{{field_name}}-{{label.name}}" value="{{label.id}}" {%if label in current_labels%}checked{%endif%}>
    <label class="form-check-label" for="{{field_name}}-{{label.name}}">
      <span class="badge rounded-pill field-editable" style="background:{{label.color}}">{{label.name}}</span>
    </label>
  </div>
    {% endfor %}
  {%else%}
    <input type="text" name="{{field_name}}" value="{{field_value}}" autofocus>
  {% endif %}
    <button type="submit">💾</button>
    <button class="btn">Cancel</button>
</form>

templates/nibble/forms/card_field.html
{% if field_name == "label" %}
    {% for label in field_value.all %}
        <span class="badge rounded-pill" style="background:{{label.color}}">{{label.name}}</span>
    {% endfor %}
{% else %}
    <span hx-get="{% url 'nibble:card_edit' card_id field_name %}" 
    hx-target="this" 
    hx-swap="outerHTML" class="field-editable">
        {{field_value}}
    </span>
{% endif %}

templates/nibble/forms/checklist_edit_form.html
<form hx-post="{% url 'nibble:checklist_edit' checklist_id field_name %}" hx-target="this" hx-swap="outerHTML" class="swappableClass">
    {% csrf_token %}
      <input type="text" name="{{field_name}}" value="{{field_value}}" autofocus>
      <button type="submit">💾</button>
      <button class="btn">Cancel</button>
  </form>

templates/nibble/forms/checklist_field.html
<span hx-get="{% url 'nibble:checklist_edit' checklist_id field_name %}" 
hx-target="this" 
hx-swap="outerHTML" class="field-editable">
{{field_value}}
</span>

templates/nibble/forms/comment_edit_form.html
<form hx-post="{% url 'nibble:comment_edit' comment.id %}" hx-target="#comment-{{comment.id}}-content" hx-swap="outerHTML" hx-on::after-request="this.reset()" class="swappableClass">
    {% csrf_token %}
      <textarea name="content">{{comment.content}}</textarea>
      <input type="hidden" name="card" value="{{comment.card.id}}">
      <input type="hidden" name="author" value="{{comment.author.id}}">
      <button type="submit">💾</button>
  </form>

templates/nibble/forms/comment_field.html
<span class="comment {% if comment.author.user.id == user.id %}field-editable{% endif %}" hx-get="{% url 'nibble:comment_edit' comment.id %}" hx-target="this" hx-swap="outerHTML"> {{comment.content}} </span>

templates/nibble/forms/delete_confirmation_modal.html
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteModalLabel">Delete {{task.name}}?</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <form hx-delete="{% url 'nibble:task_delete' task.id %}" hx-target="#li{{task.id}}for{{checklist.id}}" hx-swap="delete" hx-on::after-request="this.reset(); bootstrap.Modal.getInstance(document.getElementById('deleteModal')).hide()"
                class="swappableClass">
                <div class="modal-body">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Delete!</button>
                    <button type="button" data-bs-dismiss="modal">Cancel</button>
            </form>
        </div>
    </div>
</div>

templates/nibble/forms/task_create_form.html
<form hx-post="{% url 'nibble:task_create' %}" hx-target="#checklist{{checklist_id}}" hx-swap="beforeend" hx-on::after-request="this.reset();" class="swappableClass">
    {% csrf_token %}
    <div class="input-group mb-3">
        <div class="form-floating"> 
            <select class="form-select" id="selectPriority" name="priority">
                <option selected value="">None</option>
                {% for key, detail in priorities.items %}
                <option value="{{key}}">{{detail.icon}} {{detail.label}}</option>
                {% endfor %}
            </select>
            <label for="selectPriority">Priority</label>
        </div>

        <div class="form-floating"> 
            <select class="form-select" id="selectTaskType" name="task_type">
                <option selected value="">None</option>
                {% for type in task_types %}
                <option value="{{type.id}}">{{type.icon}} {{type.name}}</option>
                {% endfor %}
                <option value="" disabled>❓ Inne</option>
            </select>
            <label for="selectTaskType">Type</label>
        </div>          
        <!--
            https://getbootstrap.com/docs/5.3/forms/layout/

            Layout the form
            +
            Make the Select buttons icons (like 👤 for assigned)
        -->
       
 
        <div class="form-floating"> 
            <input type="date" class="form-control" id="selectDueDate" name="due_date" placeholder="Due date"/>
            <label for="selectDueDate">Due date</label>
        </div>

        <div class="form-floating"> 
            <input type="time" class="form-control" id="selectDueTime" name="due_time" placeholder="Due time"/>
            <label for="selectDueDate">Due time</label>
        </div>
   
        <div class="form-floating">
            <input type="text" class="form-control" id="taskName" name="name" placeholder="Task Name" required autofocus>
            <label for="taskName">Task name</label>
        </div>
        <div class="form-floating">
            <input type="number" name="points" id="taskPoints" class="form-control" placeholder="Points" required>
            <label for="taskPoints">Points</label>
        </div>

        <div class="form-floating">
            <select class="form-select" id="selectAssigned" name="assigned_to">
                <option selected value="">None</option>
                {% for profile in user_list %}
                <option value="{{profile.id}}">{{profile.avatar}} {{profile.user.username}}</option>
                {% endfor %}
            </select>
            <label for="selectAssigned">Assigned</label>
        </div>
    
        <input type="hidden" name="checklist" value="{{checklist_id}}">
        <button type="submit" class="btn">💾</button>
      </div>
</form>

templates/nibble/forms/task_edit_form.html
<form hx-post="{% url 'nibble:task_edit' task_id field_name %}" hx-target="#li{{task_id}}for{{checklist_id}}" hx-swap="outerHTML" class="swappableClass">
  {% csrf_token %}
  {% if field_name == "due_date" %}
    <input type="date" name="{{field_name}}" value="{{field_value}}">
  {% elif field_name == "due_time" %}
    <input type="time" name="{{field_name}}" value="{{field_value}}">
  {% elif field_name == "assigned_to" %}
  <select class="form-select" id="selectAssigned" name="assigned_to">
    <option selected value="">None</option>
    {% for profile in user_list %}
    <option value="{{profile.id}}">{{profile.avatar}} {{profile.user.username}}</option>
    {% endfor %}
</select>

    {% elif field_name == "priority" %}
    <select class="form-select" id="selectPriority" name="priority">
      <option selected value="">None</option>
      {% for key, detail in priorities.items %}
      <option value="{{key}}">{{detail.icon}} {{detail.label}}</option>
      {% endfor %}
  </select>

  {% elif field_name == "task_type" %}
  <select class="form-select" id="selectTaskType" name="task_type">
    <option selected value="">None</option>
    {% for type in task_types %}
    <option value="{{type.id}}">{{type.icon}} {{type.name}}</option>
    {% endfor %}
    <option value="" disabled>❓ Inne</option>
</select>

  {% else %}
    <input type="text" name="{{field_name}}" value="{{field_value}}" autofocus>
  {% endif %}
  <button type="submit">💾</button>
  <button type="button" class="btn">Cancel</button>
</form>

templates/nibble/forms/task_field.html
<span hx-get="{% url 'nibble:task_edit' task_id field_name %}" 
hx-target="this" 
hx-swap="outerHTML">
{{field_value}}
</span>