urls.py
from django.urls import path
from . import views

app_name = "nibble"

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('board/<int:pk>', views.BoardView.as_view(), name='board'),
    path('archive/<int:pk>', views.ArchiveView.as_view(), name='archive'),
    # Card views
    path('card/<int:pk>', views.CardView.as_view(), name='card'),
    path('card/create/', views.CardCreateView.as_view(), name='card_create'),
    path('card/edit/<int:card_id>/<str:field_name>/', views.CardEditView.as_view(), name="card_edit"),
    # Attachment views
    path('attachment/create/', views.AttachmentCreateView.as_view(), name='attachment_create'),
    path('attachment/edit/<int:attachment_id>/', views.AttachmentEditView.as_view(), name="attachment_edit"),
    path('attachment/delete/<int:pk>', views.AttachmentDeleteView.as_view(), name="attachment_delete"),
    # Comment views
    path('comment/create/', views.CommentCreateView.as_view(), name='comment_create'),
    path('comment/edit/<int:comment_id>', views.CommentEditView.as_view(), name="comment_edit"),
    path('comment/delete/<int:pk>', views.CommentDeleteView.as_view(), name="comment_delete"),
    # Checklist views
    path('checklist/create', views.ChecklistCreateView.as_view(), name="checklist_create"),
    path('checklist/edit/<int:checklist_id>/<str:field_name>/', views.ChecklistEditView.as_view(), name="checklist_edit"),
    path('checklist/delete/<int:pk>', views.ChecklistDeleteView.as_view(), name="checklist_delete"),
    # Task views
    path('task/create', views.TaskCreateView.as_view(), name="task_create"),
    path('task/edit/<int:task_id>/<str:field_name>/', views.TaskEditView.as_view(), name="task_edit"),
    path('task/delete/<int:pk>', views.TaskDeleteView.as_view(), name="task_delete"),
    # Profile views
    path('profile/<str:handle>',views.ProfileDetailView.as_view(), name='profile'),

]

templates/nibble/archive.html
{% extends "nibble/base.html" %}
{% block "title" %}{{archive.name}}{% endblock %}
{% block "content" %}

<div id="board-container">
    <h1 class="text">{{archive.name}}</h1>
    
    <div class="board-wrapper">
        {% for column in columns %}
        <div class="column" id="column{{column.id}}">
            <h3>{{column.name}}</h3>
            {% include "nibble/forms/card_create_form.html" with column=column.id %}
            {% for card in column.card_list %}
            {% include "nibble/partials/card-small.html" with card=card %}
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/nibble/base.html
{% load nibble_tags %}
<!DOCTYPE html>
<html data-bs-theme="dark">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>{% block "title" %}{% endblock %} || Nibble board</title>
  <!-- WORK ON URLS STATIC FILES -->
  <link href="style.css" rel="stylesheet" type="text/css" />
  <!-- /WORK ON URLS STATIC FILES -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
  <script src="https://unpkg.com/htmx.org@2.0.4"></script>

  <style>
    html {
  height: 100%;
  width: 100%;
}

.commenter {
  font-weight: bold;
  }

.ping {
  color: pink;
}

li.task-finished label span {
  text-decoration: line-through;
  font-style: italic;
  color: gray !important;
}

.field-editable:hover {
  background-color: rgb(83, 83, 83) !important;
  cursor: pointer;
}

.text-bg-primary.field-editable:hover {
  background-color: #3b89ff !important;
  cursor: pointer;
}

.task-project-anchor {
  text-decoration: underline;
  color: pink;
  font-weight: bold;
}

/* Container to hold everything */
#board-container {
  text-align: center;
  padding: 20px;
}

/* Ensure the wrapper scrolls horizontally */
.board-wrapper {
  display: flex;
  flex-wrap: nowrap; /* Prevent wrapping */
  overflow-x: auto; /* Enable horizontal scrolling */
  -webkit-overflow-scrolling: touch; /* Smooth scrolling on mobile */
  padding: 10px 0;
}

/* Individual columns */
.column {
  min-width: 80vw; /* Each column takes up almost the full viewport */
  max-width: 400px; /* Prevents columns from being too wide */
  flex: 0 0 auto; /* Prevents shrinking */
  min-height: 85vh;
  height: fit-content;
  border-radius: 10px;
  padding: 10px;
  margin: 0 10px;
  box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.1);
  border: 1px solid #ddd;
}

/* Cards inside the columns */
.card, .board-card {
  border: 1px solid #ddd;
  padding: 10px;
  margin: 5px 0;
  border-radius: 5px;
  box-shadow: 1px 1px 5px rgba(0, 0, 0, 0.1);
}


.partof {
  font-size: small;
  font-style: italic;
}

  </style>
</head>

<body hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}'>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'nibble:index' %}">Nibble</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% installed_apps as modules %}

          {% if modules %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Other apps
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'mischief:index' %}">Mischief</a></li>
              {% for module in modules %}
              {% with module|add:":index" as url_name %}
              <li><a class="dropdown-item" href="{% url url_name %}">{{module|capfirst}}</a></li>
              {% endwith %}
              {% endfor %}
            </ul>
          </li>
          {% endif %}
          <!-- Preparing code for the future feature of organizations -->
          {% if organizations %}
            {% for org in organizations %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{org.name}}
              </a>
              <ul class="dropdown-menu">
                {% for board in org.boards.all %}
                <li><a class="dropdown-item" href="#">{{board.name}}</a></li>
                {% endfor %}
              </ul>
            </li>
            {% endfor %}

          {% else %}
          <li class="nav-item">
            <!-- TODO: List of boards user is a part of -->
            <a class="nav-link" href="{% url 'nibble:board' 1%}">Board</a>
          </li>
          {% endif %}
                     
          <li class="nav-item">
            <!-- TODO: List of all archives for the organization -->
            <a class="nav-link" href="{% url 'nibble:archive' 2%}">Archive</a>
          </li>
        </ul>
        <span class="navbar-text">
          <a href="{% url 'nibble:profile' user.nibbleProfile.handle %}">{{user.nibbleProfile.handle}}</a>
        </span>
      </div>
    </div>
  </nav>

   {% block "content" %}{% endblock %}

</body>

</html>

templates/nibble/board.html
{% extends "nibble/base.html" %}
{% block "title" %}{{board.name}}{% endblock %}
{% block "content" %}

<div id="board-container">
    <h1 class="text">{{board.name}}</h1>
    
    <div class="board-wrapper">
        {% for column in columns %}
        <div class="column" id="column{{column.id}}">
            <h3>{{column.name}}</h3>
            {% include "nibble/forms/card_create_form.html" with column=column.id %}
            {% for card in column.card_list %}
            {% include "nibble/partials/card-small.html" with card=card %}
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/nibble/card.html
{% extends "nibble/base.html" %}
{% block "title" %}{{card.name}}{% endblock %}
{% block "content" %}

<div id="deleteModal"></div>

<div class="project-card">
    <div id="project-toolbar">
        <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample"
            aria-controls="offcanvasExample">
            Toolbar
        </button>

        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasExample"
            aria-labelledby="offcanvasExampleLabel">
            <div class="offcanvas-header">
                <h3 class="offcanvas-title" id="offcanvasExampleLabel"> Toolbar</h3>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">

                <button>📄 COPY</button> <br />
                <button> ➡️ MOVE </button> <br />
                <button> 👁️ WATCH/STOP WATCHING </button> <br />
                <button> 🗃️ ARCHIVE </button> <br />
                <button> 🔄 COPY LINK </button> <br />
            </div>
        </div>
    </div>
    <div class="project-header">
        <div class="labels">
            <div id="label-list" style="display:inline">
                {% for label in card.label.all %}
                    <span class="badge rounded-pill" style="background:{{label.color}}">{{label.name}}</span>
                {% endfor %}            
            </div>
            <button hx-get="{% url 'nibble:card_edit' card.id 'label' %}" hx-target="#label-list" hx-swap="innerHTML">+</button>
        </div>
        <div>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'nibble:board' card.column.board.id %}">{{card.column.board.name}}</a></li>
                    <li class="breadcrumb-item">{{card.column.name}}</li>
                    <li class="breadcrumb-item active" aria-current="page">{{card.name}}</li>
                </ol>
            </nav>
        </div>

        <div id="protect-assigned" style="color:red;">
            <!-- Change them to unique later in the CardDetailView -->
            {% for checklist in card.checklists.all%}
                {% for task in checklist.tasks.all %}
                {{task.assigned_to.avatar}}
                {% endfor %}
            {% endfor %}
        </div>

        <div id="project-title">
            <h1>
                {% include "nibble/forms/card_field.html" with card_id=card.id field_name='name' field_value=card.name%}
            </h1>
        </div>
    </div>

    <div id="project-body">
        <div id="project-description">
            <div id="info-header">
                {% if card.owner %}
             
                Owner: {% include "nibble/forms/card_field.html" with card_id=card.id field_name='owner' field_value=card.owner.avatar%} <a href="{% url 'nibble:profile' card.owner.handle %}">  {{card.owner.user.username}} </a> <br />
                {%else%}
                Owner: <span hx-get="{% url 'nibble:card_edit' card.id 'owner' %}" hx-target="this" hx-swap="outerHTML">+</span>
                {% endif %}
            
                {% if card.helper %}
                Helper: {% include "nibble/forms/card_field.html" with card_id=card.id field_name='helper' field_value=card.helper.avatar%} <a href="{% url 'nibble:profile' card.helper.handle %}">  {{card.helper.user.username}} </a> <br />
                {%else%}
                Helper: <span hx-get="{% url 'nibble:card_edit' card.id 'helper' %}" hx-target="this" hx-swap="outerHTML" class="field-editable">+</span>

                {% endif %}
                
                {% if card.due_datetime %}
                <span hx-get="{% url 'nibble:card_edit' card.id 'due_datetime' %}" hx-target="this" hx-swap="outerHTML" class="field-editable">📅🕕{{card.due_datetime}}</span>
                {% endif %}
            </div>
            <br />
            <div class="attachments">

                <h3>
                    Attachments
                    <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseAddAttachment" aria-expanded="false" aria-controls="collapseAddAttachment"> + </button>
                </h3>
    
                </p>
                <div class="collapse" id="collapseAddAttachment">
                    <form hx-post="{% url 'nibble:attachment_create' %}" hx-target="#attachments-list" hx-swap="beforeend" hx-on::after-request="this.reset(); bootstrap.Collapse.getInstance(document.getElementById('collapseAddAttachment')).hide()" class="swappableClass">
                        {% csrf_token %}
                          <input type="text" name="name" placeholder="Name" autofocus required>
                          <input type="url" name="url" placeholder="URL" autofocus required>
                          <input type="hidden" name="card" value="{{card.id}}">
                          <button type="submit">💾</button>
                      </form>
                </div>

                <ul id="attachments-list">
                    {% for attachment in card.attachments.all %}
                    <li id="attachment-{{attachment.id}}">
                        <a href="{{attachment.url}}">{{attachment.name}}</a>
                        <button hx-get="{% url 'nibble:attachment_edit' attachment.id %}" hx-target="this" hx-swap="outerHTML">🖋️</span>
                        {% if can_delete_attachment %}
                        <button hx-post="{% url 'nibble:attachment_delete' attachment.id %}" hx-target="#deleteModal" hx-swap="outerHTML">🗑️</button>
    {% endif %}
                    </li>
                    
                    {% empty %}
                    <p hx-get="{% url 'nibble:card_edit' card.id 'attachment' %}" hx-target="this" hx-swap="outerHTML"> No attachments added yet. </p>
                    {% endfor %}
                </ul>

            </div>

            <br />
            <div id="description">
                <h3>
                    Description
                </h3>
                    {% if card.description %}
                    <p>
                        {% include "nibble/forms/card_field.html" with card_id=card.id field_name='description' field_value=card.description%}
                    </p>
                    {% else %}
                    <div class="muted" hx-get="{% url 'nibble:card_edit' card.id 'description' %}" hx-target="this" hx-swap="outerHTML">No description provided yet. Click and add one!</div>
                    {% endif %}
            </div>
        </div>

        <div id="project-lists-all">
            <h3>
                Checklists
                <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseAddChecklist" aria-expanded="false" aria-controls="collapseAddChecklist"> + </button>
            </h3>

            </p>
            <div class="collapse" id="collapseAddChecklist">
                <form hx-post="{% url 'nibble:checklist_create' %}" hx-target="#project-lists-all" hx-swap="beforeend" hx-on::after-request="this.reset(); bootstrap.Collapse.getInstance(document.getElementById('collapseAddChecklist')).hide()" class="swappableClass">
                    {% csrf_token %}
                      <input type="text" name="name" autofocus required>
                      <input type="hidden" name="card" value="{{card.id}}">
                      <button type="submit">💾</button>
                  </form>
            </div>

            {% for checklist in card.checklists.all %}
                {% include "nibble/partials/checklist.html" with checklist=checklist %}
            {% endfor %}

        </div>
    </div>
        <div id="project-footer">
            <div id="logs">
                <h5> Logs
                    <button class="btn btn-primary" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapseLogs" aria-expanded="false" aria-controls="collapseLogs">
                        v
                    </button>
                </h5>

                {% include "nibble/partials/logs.html" %}

            </div>

             <div id="comments">
                    <h5> Comments
                        <button class="btn btn-primary" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseComments" aria-expanded="false" aria-controls="collapseComments">
                            v
                        </button>
                    </h5>
                    {% include "nibble/partials/comments.html" with comments=card.comments.all %}
            </div>
        </div>
    </div>
</div>
    


{% endblock %}

templates/nibble/index.html
{% extends "nibble/base.html" %}
{% block "title" %}Nibble board{% endblock %}
{% block "content" %}
{{message}}! &lt;:3~
{% endblock %}

templates/nibble/index_anonymous.html
<h1>Hello, stranger!</h1>
<h2>What's Nibble?</h2>
<p><b>Nibble</b>, my friend, is an easy way to nibble away at your tasks!</p>

templates/nibble/profile.html
{% extends "nibble/base.html" %}
{% block "title" %}{{profile.user.username}}{% endblock %}
{% block "content" %}

<div class="user-profile">
    <div class="user-profile-header">

        <h1><img />{{profile.avatar}} {{profile.user.username}}</h1>
        <h6><i>@{{profile.handle}}</i></h6>
        <h4>{{profile.specialization}}</h4>
        <p><b>Points:</b> {{profile.points}}</p>
        <p id="bio">{{profile.bio}}</p>
    </div>

    <div class="user-profile-activity">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            {% for year, _ in tasks_by_year.items %}
            <li class="nav-item" role="presentation">
                <button class="nav-link {% if forloop.first %}active{% endif %}"" id="{{year}}-tab" data-bs-toggle="tab" data-bs-target="#{{year}}-tab-pane"
                    type="button" role="tab" aria-controls="{{year}}-tab-pane" aria-selected="{% if forloop.first %}true{%else%}false{% endif %}">{{year}}</button>
            </li>
            {% endfor %}

            <li class="nav-item" role="presentation">
                <button class="nav-link" id="temp-tab" data-bs-toggle="tab" data-bs-target="#temp-tab-pane"
                    type="button" role="tab" aria-controls="temp-tab-pane" aria-selected="false">Temp</button>

            </li>
        </ul>
        {% for year, tasks in tasks_by_year.items %}
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade {% if forloop.first %}show active{% endif %}" id="{{year}}-tab-pane" role="tabpanel" aria-labelledby="{{year}}-tab"
                tabindex="{{year}}">

                <button>+</button>
                <div>
                    <!--make it collapsible-->
                    <div class="input-group mb-3">
                        <button class="btn btn-outline-secondary dropdown-toggle" type="button"
                            data-bs-toggle="dropdown" aria-expanded="false">Type</button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">CAT1</a></li>
                            <li><a class="dropdown-item" href="#">CAT2</a></li>
                            <li><a class="dropdown-item" href="#">CAT3</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Custom</a></li>
                        </ul>

                        <button class="btn btn-outline-secondary dropdown-toggle" type="button"
                            data-bs-toggle="dropdown" aria-expanded="false">Priority</button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">🔴 Urgent</a></li>
                            <li><a class="dropdown-item" href="#">🟠 Important</a></li>
                            <li><a class="dropdown-item" href="#">🟡 </a></li>
                            <li><a class="dropdown-item" href="#">🟢 </a></li>
                        </ul>

                        <input type="date" placeholder="Date" class="btn" text="...m" />

                        <!-- Make the button smaller -->


                        <!-- TODO: Custom otwiera modal w którym się podaje wartość. Albo otwiera kolejny collapse, ale modal lepiej wyglądać będzie -->

                        <input type="text" class="form-control" aria-label="Text input with dropdown button">
                    </div>
                </div>

                <ul class="list-group list-group-flush">
                    {% for task in tasks %}
                    <li class="list-group-item {% if task.is_finished %}task-finished{% endif %}">
                        {% if task.priority %}
                        <span>{{task.priority}}</span>
                        {% endif %}
                        <span>{{task.name}}</span>
                        {% if task.due_datetime %}
                        <span>📅 {{task.due_datetime|date:"d/m"}} | 🕕 {{task.due_datetime|date:"H:i"}}</span>
                        {% endif %}
                        <span class="badge text-bg-primary rounded-pill">{{task.points}} pts</span>
                        {% if task.assigned_to %}
                        <span class="task-assigned">{{task.assigned_to.avatar}}</span>
                        {% else %}
                        <span>{{task.task_type.name}}</span>
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>
                <!-- TODO: Merge tasks from the same project into one and sum the points -->
                <!-- TODO: priority for tasks as a 🔴🟠🟡🟢; for people who see no color it might also have a number inside or something -->
                <!-- https://getbootstrap.com/docs/5.3/components/list-group/ tu jest pokazane zeby pill był po prawo -->
            </div>
            {% endfor %}
            <div class="tab-pane fade" id="temp-tab-pane" role="tabpanel" aria-labelledby="temp-tab" tabindex="0">
                <button>+</button>
                <div>
                    <!--make it collapsible-->
                    <div class="input-group mb-3">
                        <button class="btn btn-outline-secondary dropdown-toggle" type="button"
                            data-bs-toggle="dropdown" aria-expanded="false">Type</button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">CAT1</a></li>
                            <li><a class="dropdown-item" href="#">CAT2</a></li>
                            <li><a class="dropdown-item" href="#">CAT3</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Custom</a></li>
                        </ul>

                        <button class="btn btn-outline-secondary dropdown-toggle" type="button"
                            data-bs-toggle="dropdown" aria-expanded="false">Priority</button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">🔴 Urgent</a></li>
                            <li><a class="dropdown-item" href="#">🟠 Important</a></li>
                            <li><a class="dropdown-item" href="#">🟡 </a></li>
                            <li><a class="dropdown-item" href="#">🟢 </a></li>
                        </ul>

                        <input type="date" placeholder="Date" class="btn" text="...m" />
                        <input type="text" class="form-control" aria-label="Text input with dropdown button">
                    </div>
                </div>
                <ul class="list-group list-group-flush">
                </ul>
            </div>
        </div>
    </div>

    <div id="project-footer">
        <div id="logs">
            <h5> Logs
                <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseLogs"
                    aria-expanded="false" aria-controls="collapseLogs">
                    v
                </button>
            </h5>
            {% include "nibble/partials/logs.html" %}
        </div>
    </div>
</div>

{% endblock %}