urls.py
from django.urls import path
from . import views

app_name = "nibble"

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('board/<int:pk>', views.BoardView.as_view(), name='board'),
    path('archive/<int:pk>', views.ArchiveView.as_view(), name='archive'),
    # Card views
    path('card/<int:pk>', views.CardView.as_view(), name='card'),
    path('card/create/', views.CardCreateView.as_view(), name='card_create'),
    path('card/edit/<int:card_id>/<str:field_name>/', views.CardEditView.as_view(), name="card_edit"),
    # Attachment views
    path('attachment/create/', views.AttachmentCreateView.as_view(), name='attachment_create'),
    path('attachment/edit/<int:attachment_id>/', views.AttachmentEditView.as_view(), name="attachment_edit"),
    path('attachment/delete/<int:pk>', views.AttachmentDeleteView.as_view(), name="attachment_delete"),
    # Comment views
    path('comment/create/', views.CommentCreateView.as_view(), name='comment_create'),
    path('comment/edit/<int:comment_id>', views.CommentEditView.as_view(), name="comment_edit"),
    path('comment/delete/<int:pk>', views.CommentDeleteView.as_view(), name="comment_delete"),
    # Checklist views
    path('checklist/create', views.ChecklistCreateView.as_view(), name="checklist_create"),
    path('checklist/edit/<int:checklist_id>/<str:field_name>/', views.ChecklistEditView.as_view(), name="checklist_edit"),
    path('checklist/delete/<int:pk>', views.ChecklistDeleteView.as_view(), name="checklist_delete"),
    # Task views
    path('task/create', views.TaskCreateView.as_view(), name="task_create"),
    path('task/edit/<int:task_id>/<str:field_name>/', views.TaskEditView.as_view(), name="task_edit"),
    path('task/delete/<int:pk>', views.TaskDeleteView.as_view(), name="task_delete"),
    # Profile views
    path('profile/<str:handle>',views.ProfileDetailView.as_view(), name='profile'),

]

templates/nibble/partials/card-small.html
<div class="board-card card">
    <div class="board-card-header">
        <div class="board-card-info">
             <span>⚙️</span>
            <!-- ⚙️ tylko na PC z opcjami typu 🗑️ delete, 🗃️ archive, 📄 copy; na telefonie nie ma sensu bo sie nie zmieści-->
            <br />
            {% for label in card.label.all %}
            <span class="badge rounded-pill" style="background:{{label.color}}">{{label.name}}</span>
            {% endfor %}
            <br />
            <!-- change spans to divs so i don't need this br and make it all make more sense xd -->
            <h5>
                <a href="{% url 'nibble:card' card.id %}">{{card.name}}</a>
            </h5>
            {% if card.due_datetime %}
            <span>📅🕕{{card.due_datetime}}</span>
            {% endif %}
            {% if card.owner %}
            || <span>👤</span>
            {% endif %}
            {% if card.helper %}
            <span>👤</span>
            {% endif %}
        </div>
        {% for i in card.attachments.all %}
        🔄
        {% endfor %}
       
        {% if card.checklists %}
            {% for checklist in card.checklists.all %}
            ☑️
            {% endfor %}
        {% endif %}

        <!-- TODO: Show number of attachments instead of an emoji for each 
        +
        Show the number of finished tasks of all tasks, as in 2/10, 21/30 -->
    </div>

</div>

templates/nibble/partials/checklist.html
<div id="Checklist{{checklist.id}}">
    {% include "nibble/forms/checklist_field.html" with checklist=checklist checklist_id=checklist.id field_name='name' field_value=checklist.name %} 
    <button class="btn btn-primary" type="button" data-bs-toggle="collapse"
        data-bs-target="#collapseChecklist{{checklist.id}}" aria-expanded="false" aria-controls="collapseChecklist{{checklist.id}}">
        v
    </button>
    {% if can_delete_checklist %}
        <button hx-delete="{% url 'nibble:checklist_delete' checklist.id %}" hx-target="#collapseChecklist{{checklist.id}}" hx-swap="delete">🗑️</button>
    {% endif %}
</div>

<div class="collapse show" id="collapseChecklist{{checklist.id}}">
    <div class="card card-body">
        <ul class="list-group" id="checklist{{checklist.id}}">
            {% for task in checklist.tasks.all %}
            {% include "nibble/partials/task.html" with task=task checklist=checklist %} 
            {% endfor %}
        </ul>

        <hr />
        <div class="add-task">
            <form hx-get="{% url 'nibble:task_create' %}" hx-target="this" hx-swap="outerHTML" class="swappableClass">
                <input type="hidden" name="checklist_id" value="{{checklist.id}}">
                <button type="submit">Add new</button>
            </form>
        </div>
        
</div>
</div>

templates/nibble/partials/comments.html
<div class="collapse show" id="collapseComments">

    <form hx-post="{% url 'nibble:comment_create' %}" hx-target="#collapseComments" hx-swap="afterend" hx-on::after-request="this.reset()" class="swappableClass">
        {% csrf_token %}
          <textarea name="content"></textarea>
          <input type="hidden" name="card" value="{{card.id}}">
          <input type="hidden" name="author" value="{{user.nibbleProfile.id}}">
          <button type="submit">💾</button>
      </form>
<br /><br />


        {% for comment in comments %}
        <div class="comment-entry" id="comment-{{comment.id}}">
            <div class="comment-date text-muted">{{comment.datetime}}</div>
            <span class="commenter"><img />👤 {{comment.author.user.username}}:</span>
            <span id="comment-{{comment.id}}-content">
                <span class="comment {% if comment.author.user.id == user.id %}field-editable{% endif %}" hx-get="{% url 'nibble:comment_edit' comment.id %}" hx-target="this" hx-swap="outerHTML"> {{comment.content}} </span>
            </span>


            {% if comment.author.user.id == user.id %}
                <button hx-delete="{% url 'nibble:comment_delete' comment.id %}" hx-target="#comment-{{comment.id}}" hx-swap="delete">🗑️</button>
            {% endif %}

        </div>
        {% empty %}
        No comments yet!
        {% endfor %}
</div>

<!-- change .commenter to .nick? or just bold, I doubt I'd have to get this specific to have .commenter -->

templates/nibble/partials/logs.html
<div class="collapse" id="collapseLogs">
    <div>
        <div class="log-entry">
            <div class="log-date text-muted">23.12.2012, 13:37</div>
            <p class="log-description"><b>👤Person1</b> added a task <i>Test 123</i></p>
        </div>
        <div class="log-entry">
            <div class="log-date text-muted">02.01.2025, 17:13</div>
            <p class="log-description"><b>👤Person3</b> renamed <i>AAA</i> to <i>An Actual Task!</i></p>
        </div>
        <div class="log-entry">
            <div class="log-date text-muted">16.05.2027, 20:01</div>
            <p class="log-description"><b>👤Person1</b> assigned <b>👤 Person5</b> to task <i>Make it
                    great
                    again</i></p>
        </div>
        <div class="log-entry">
            <div class="log-date text-muted">16.05.2027, 20:01</div>
            <p class="log-description"><b>👤Person1</b> finished task <i>Make it great again</i> X days
                before the
                deadline/<u><b>X days late</b></u></p>
            <!-- good idea to keep track because it helps to see patterns in people for yearly feedbacks -->
        </div>
    </div>
</div>

templates/nibble/partials/task.html
<li class="list-group-item {% if task.is_finished %} task-finished {% endif %}" id="li{{task.id}}for{{checklist.id}}">
    <input hx-post="{% url 'nibble:task_edit' task.id 'is_finished' %}" hx-target="#li{{task.id}}for{{checklist.id}}" hx-swap="outerHTML" name="is_finished" class="form-check-input me-1" type="checkbox"
    id="Checkbox{{task.id}}For{{checklist.id}}" {% if task.is_finished %} checked {% endif %}>
    <label class="form-check-label">
        
        {% if task.priority %}
        <span hx-get="{% url 'nibble:task_edit' task.id 'priority' %}" hx-target="this" hx-swap="outerHTML" class="field-editable">
            {{task.priority}}
        </span>
        {% endif %}

        <span hx-get="{% url 'nibble:task_edit' task.id 'name' %}" hx-target="this" hx-swap="outerHTML" class="field-editable">
            {{task.name}}
        </span>

        {% if task.due_date %}
        <span hx-get="{% url 'nibble:task_edit' task.id 'due_date' %}" hx-target="this" hx-swap="outerHTML" class="field-editable">
            📅 {{task.due_date}}
        </span>
        {% endif %}

        {% if task.due_time %}
        <span hx-get="{% url 'nibble:task_edit' task.id 'due_time' %}" hx-target="this" hx-swap="outerHTML" class="field-editable">
            🕕 {{task.due_time}}
        </span>
        {% endif %}


        <span hx-get="{% url 'nibble:task_edit' task.id 'points' %}" hx-target="this" hx-swap="outerHTML"
            class="badge text-bg-primary rounded-pill field-editable">
            {{task.points}} pts
        </span>


        {% if task.assigned_to %}
        <span hx-get="{% url 'nibble:task_edit' task.id 'assigned_to' %}" hx-target="this" hx-swap="outerHTML"
            class="task-assigned field-editable">
            {{task.assigned_to}}
        </span>
        {% else %}
        <span hx-get="{% url 'nibble:task_edit' task.id 'task_type' %}" hx-target="this" hx-swap="outerHTML" class="field-editable">
            {{task.task_type}}
        </span>
        {% endif %}
    </label>

    {% if can_delete_task %}
    <button hx-get="{% url 'nibble:task_delete' task.id %}" hx-target="#deleteModal" hx-swap="outerHTML" hx-on::after-request="setTimeout(() => bootstrap.Modal.getOrCreateInstance(document.getElementById('deleteModal')).show(), 100)">🗑️</button>
    {% endif %}


</li>